package physicscalculator;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author User
 */
public class MainFrame extends javax.swing.JFrame{
    public String newParamName = null;
    public String fileName = null;
    public JTextField []paramTextFields = new JTextField[10];
    public JScrollPane []paramScrollPanes = new JScrollPane[10]; 
    public JList []paramLists = new JList[10]; 
    public JButton []paramButtons = new JButton[10];
    
    public MainFrame() {
        initComponents();
        
        paramTextFields[0] = param0;
        paramTextFields[1] = param1;
        paramTextFields[2] = param2;
        paramTextFields[3] = param3;
        paramTextFields[4] = param4;
        paramTextFields[5] = param5;
        paramTextFields[6] = param6;
        paramTextFields[7] = param7;
        paramTextFields[8] = param8;
        paramTextFields[9] = param9;
        
        paramScrollPanes[0] = jScrollPane0;
        paramScrollPanes[1] = jScrollPane1;
        paramScrollPanes[2] = jScrollPane2;
        paramScrollPanes[3] = jScrollPane3;
        paramScrollPanes[4] = jScrollPane4;
        paramScrollPanes[5] = jScrollPane5;
        paramScrollPanes[6] = jScrollPane6;
        paramScrollPanes[7] = jScrollPane7;
        paramScrollPanes[8] = jScrollPane8;
        paramScrollPanes[9] = jScrollPane9;
       
        paramLists[0] = jList0;
        paramLists[1] = jList1;
        paramLists[2] = jList2;
        paramLists[3] = jList3;
        paramLists[4] = jList4;
        paramLists[5] = jList5;
        paramLists[6] = jList6;
        paramLists[7] = jList7;
        paramLists[8] = jList8;
        paramLists[9] = jList9;
        
        paramButtons[0] = editParam0;
        paramButtons[1] = editParam1;
        paramButtons[2] = editParam2;
        paramButtons[3] = editParam3;
        paramButtons[4] = editParam4;
        paramButtons[5] = editParam5;
        paramButtons[6] = editParam6;
        paramButtons[7] = editParam7;
        paramButtons[8] = editParam8;
        paramButtons[9] = editParam9;
        
        setInvisible();
        setParam(5);
    }
    public void setInvisible(){
        for (int i = 0; i < paramTextFields.length; i++){
            paramTextFields[i].setVisible(false);
            paramScrollPanes[i].setVisible(false);
            paramLists[i].setVisible(false);
            paramButtons[i].setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jDialogEditParam = new javax.swing.JDialog();
        dispParam = new javax.swing.JScrollPane();
        dispParamList = new javax.swing.JList<>();
        editParamAdd = new javax.swing.JButton();
        editParamApply = new javax.swing.JButton();
        editParamClose = new javax.swing.JButton();
        setParamCount = new javax.swing.JButton();
        paramCount = new javax.swing.JTextField();
        param0 = new javax.swing.JTextField();
        param1 = new javax.swing.JTextField();
        param2 = new javax.swing.JTextField();
        param3 = new javax.swing.JTextField();
        param4 = new javax.swing.JTextField();
        param5 = new javax.swing.JTextField();
        param6 = new javax.swing.JTextField();
        param7 = new javax.swing.JTextField();
        param8 = new javax.swing.JTextField();
        param9 = new javax.swing.JTextField();
        jScrollPane0 = new javax.swing.JScrollPane();
        jList0 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList8 = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList9 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        openFile = new javax.swing.JButton();
        editParam0 = new javax.swing.JButton();
        editParam1 = new javax.swing.JButton();
        editParam2 = new javax.swing.JButton();
        editParam3 = new javax.swing.JButton();
        editParam4 = new javax.swing.JButton();
        editParam5 = new javax.swing.JButton();
        editParam6 = new javax.swing.JButton();
        editParam7 = new javax.swing.JButton();
        editParam8 = new javax.swing.JButton();
        editParam9 = new javax.swing.JButton();

        jDialog1.setTitle("Open file");
        jDialog1.setMinimumSize(new java.awt.Dimension(600, 400));
        jDialog1.setSize(new java.awt.Dimension(600, 400));

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jFileChooser1, java.awt.BorderLayout.CENTER);

        jDialogEditParam.setMinimumSize(new java.awt.Dimension(400, 400));
        jDialogEditParam.setPreferredSize(new java.awt.Dimension(250, 430));
        jDialogEditParam.setSize(getPreferredSize());
        jDialogEditParam.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dispParam.setViewportView(dispParamList);

        jDialogEditParam.getContentPane().add(dispParam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 370));

        editParamAdd.setText("Add");
        editParamAdd.setPreferredSize(new java.awt.Dimension(60, 23));
        jDialogEditParam.getContentPane().add(editParamAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        editParamApply.setText("Apply");
        editParamApply.setPreferredSize(new java.awt.Dimension(60, 23));
        jDialogEditParam.getContentPane().add(editParamApply, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        editParamClose.setText("Close");
        editParamClose.setPreferredSize(new java.awt.Dimension(60, 23));
        editParamClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editParamCloseActionPerformed(evt);
            }
        });
        jDialogEditParam.getContentPane().add(editParamClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Physics Calculator");
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setParamCount.setText("Set");
        setParamCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setParamCountActionPerformed(evt);
            }
        });
        getContentPane().add(setParamCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        paramCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paramCountActionPerformed(evt);
            }
        });
        paramCount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paramCountKeyPressed(evt);
            }
        });
        getContentPane().add(paramCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 60, 20));
        getContentPane().add(param0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, -1));
        getContentPane().add(param1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 60, -1));
        getContentPane().add(param2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 60, -1));
        getContentPane().add(param3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 60, -1));

        param4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                param4ActionPerformed(evt);
            }
        });
        getContentPane().add(param4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 60, -1));
        getContentPane().add(param5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 60, -1));
        getContentPane().add(param6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 60, -1));
        getContentPane().add(param7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 60, -1));
        getContentPane().add(param8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 60, -1));
        getContentPane().add(param9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 60, -1));

        jScrollPane0.setViewportView(jList0);

        getContentPane().add(jScrollPane0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 370));

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, 370));

        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 60, 370));

        jScrollPane3.setViewportView(jList3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 60, 370));

        jScrollPane4.setViewportView(jList4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 60, 370));

        jScrollPane5.setViewportView(jList5);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 60, 370));

        jScrollPane6.setViewportView(jList6);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 60, 370));

        jScrollPane7.setViewportView(jList7);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 60, 370));

        jScrollPane8.setViewportView(jList8);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 60, 370));

        jScrollPane9.setViewportView(jList9);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 60, 370));

        jLabel1.setText("Param count (max 10)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 20));

        openFile.setText("Open file");
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });
        getContentPane().add(openFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        editParam0.setText("edit");
        editParam0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editParam0ActionPerformed(evt);
            }
        });
        getContentPane().add(editParam0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 60, -1));

        editParam1.setText("edit");
        getContentPane().add(editParam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 60, -1));

        editParam2.setText("edit");
        getContentPane().add(editParam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 60, -1));

        editParam3.setText("edit");
        editParam3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editParam3ActionPerformed(evt);
            }
        });
        getContentPane().add(editParam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 60, -1));

        editParam4.setText("edit");
        getContentPane().add(editParam4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 60, -1));

        editParam5.setText("edit");
        getContentPane().add(editParam5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 60, -1));

        editParam6.setText("edit");
        getContentPane().add(editParam6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 60, -1));

        editParam7.setText("edit");
        getContentPane().add(editParam7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 60, -1));

        editParam8.setText("edit");
        getContentPane().add(editParam8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 60, -1));

        editParam9.setText("edit");
        getContentPane().add(editParam9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void setParamCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setParamCountActionPerformed
        String countS = paramCount.getText();
        int count = Integer.parseInt(countS);
        setParam(count);
    }//GEN-LAST:event_setParamCountActionPerformed
    public void setParam(int count){
        setInvisible();
        for (int i = 0; i < count; i++){
            paramTextFields[i].setVisible(true);
            paramScrollPanes[i].setVisible(true);
            paramLists[i].setVisible(true);
            paramButtons[i].setVisible(true);
        }
    }
    private void param4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_param4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_param4ActionPerformed

    private void paramCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paramCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paramCountActionPerformed

    private void paramCountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paramCountKeyPressed
        int key = evt.getKeyCode();
        String countS = paramCount.getText();
        int count = 0;
        try {
            count = Integer.parseInt(countS);
        } catch (Exception e){
            
        }
        
        if (key == KeyEvent.VK_ENTER){
            setParam(count);
        }
    }//GEN-LAST:event_paramCountKeyPressed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV & TXT", "txt", "csv"); //Change later
        jFileChooser1.setFileFilter(filter);
        fileName = jFileChooser1.getSelectedFile().getPath();
        System.out.println(fileName);
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileActionPerformed
        jDialog1.setVisible(true);
    }//GEN-LAST:event_openFileActionPerformed

    private void editParam3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editParam3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editParam3ActionPerformed

    private void editParamCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editParamCloseActionPerformed
        jDialogEditParam.setVisible(false);
    }//GEN-LAST:event_editParamCloseActionPerformed

    private void editParam0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editParam0ActionPerformed
        jDialogEditParam.setVisible(true);
        loadParamData();
    }//GEN-LAST:event_editParam0ActionPerformed

    public void loadParamData(){
        DefaultListModel<String> li = new DefaultListModel<>();
        li.addElement("Hello");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane dispParam;
    private javax.swing.JList<String> dispParamList;
    private javax.swing.JButton editParam0;
    private javax.swing.JButton editParam1;
    private javax.swing.JButton editParam2;
    private javax.swing.JButton editParam3;
    private javax.swing.JButton editParam4;
    private javax.swing.JButton editParam5;
    private javax.swing.JButton editParam6;
    private javax.swing.JButton editParam7;
    private javax.swing.JButton editParam8;
    private javax.swing.JButton editParam9;
    private javax.swing.JButton editParamAdd;
    private javax.swing.JButton editParamApply;
    private javax.swing.JButton editParamClose;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialogEditParam;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList0;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList6;
    private javax.swing.JList<String> jList7;
    private javax.swing.JList<String> jList8;
    private javax.swing.JList<String> jList9;
    private javax.swing.JScrollPane jScrollPane0;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton openFile;
    private javax.swing.JTextField param0;
    private javax.swing.JTextField param1;
    private javax.swing.JTextField param2;
    private javax.swing.JTextField param3;
    private javax.swing.JTextField param4;
    private javax.swing.JTextField param5;
    private javax.swing.JTextField param6;
    private javax.swing.JTextField param7;
    private javax.swing.JTextField param8;
    private javax.swing.JTextField param9;
    private javax.swing.JTextField paramCount;
    private javax.swing.JButton setParamCount;
    // End of variables declaration//GEN-END:variables
}
